### ISSUE TITLE
Move to rubygems.org

### ISSUE THREAD

**Issue by klausbadelt** [kaspergrubbe/render_async#4]
Love this. But using a different source than rubygems.org slows down `bundle install` quite a bit. Any reason you don't want to host this on rubygems.org?

**Comment by nikolalsvk** [comment]
Hi @klausbadelt, thanks for the suggestion. 

This gem is hosted on rubygems, checkout most recent version at https://github.com/renderedtext/render_async

You should just be able to do `gem 'render_async'` in your Gemfile

**Comment by nikolalsvk** [comment]
Also, you can try out this link, I hope it helps with your problem https://rubygems.org/gems/render_async/

**Comment by kaspergrubbe** [comment]
Sorry for the confusion @klausbadelt , I have now made it clear that the project have moved to another repo https://github.com/kaspergrubbe/render_async/commit/8559d6589f558a3e1ef5172b82112b105fac7120
